from i18n import LANGS
GUIDE={
'ja':[
'1. 調査元と整理先modelsを選び、全件調査または新規調査を実行します。\n2. 識別結果と保存先を確認し、承認・拒否・保存先変更を選びます。\n3. 承認した項目だけ実行します。必要なフォルダーはこの時点で作成します。\n\nCtrl/Shiftで複数選択。ボタンに約0.6秒カーソルを置くと説明が出ます。',
'配布元のSHA256一致は同じファイルである根拠です。動作・互換性の保証ではありません。構造推定や既存フォルダー名は確認済みと区別します。\nImg2txtModels等の独自フォルダーでは、読み込みノードの設定も必要です。複数ファイル構成はまとめて保持します。\nワークフロー修正は対応する標準ローダーのみ。修正前JSONをバックアップします。',
'完全オフラインをオンにするとAPI・更新確認・プレビュー通信を停止します。端末内の調査、キャッシュ参照、整理、ログ保存は利用できます。\nオンライン検索ではハッシュと、HF検索の場合はファイル名を送信します。重みや画像は送信しません。\nプレビュー画像はメモリー内のみ。外部検索と問い合わせは利用者がブラウザーで開く操作です。',
'診断ログは端末内に保存され、自動で誰かに届くことはありません。個人パス、モデル名、認証情報、例外の詳細文は含めません。\n右上のヘルプからログを確認・保存して、設定された問い合わせ先へ利用者が渡します。GitHub Issuesの場合は公開投稿です。投稿前に確認してください。\n公開先が未設定のときは、ログ保存のみできます。',
'公開GitHubリポジトリのReleasesを参照します。起動時確認は初期状態ではオフで、利用者が有効にできます。手動確認も可能です。オフラインでは更新を知ることはできません。\n新版を検出したらリリースページを案内します。自動インストール・実行はしません。\n配布者は設定をpublisher.jsonとして書き出し、EXEの隣に置いて配布します。GitHub側にv1.3.0のような安定版タグとZIPを公開してください。'],
'en':[
'1. Choose scan and destination models folders, then scan all or new items.\n2. Review identification and destinations; approve, reject or edit.\n3. Apply approved items. Required folders are created at that point.\n\nUse Ctrl/Shift for multiple selections. Hover for 0.6 seconds to see a tooltip.',
'A SHA256 match identifies the same file; it does not guarantee runtime compatibility. Structural guesses and existing folder names are separate from verified results.\nCustom folders such as Img2txtModels also need matching loader configuration. Multi-file packages stay together.\nWorkflow repair supports selected standard loaders and backs up the original JSON.',
'Offline mode blocks API requests, update checks and image previews. Local scans, cached information, organization and log export remain available.\nOnline lookups send hashes and, for HF search, filenames. They do not upload weights or images.\nPreviews stay in memory. External search and support pages open only when you choose to open the browser.',
'Logs stay on the device; nobody receives them automatically. Reports omit personal paths, model names, credentials and exception messages.\nReview and save a report from Help, then share it through the configured support destination yourself. GitHub Issues are public; review before posting.\nWithout a publisher destination, you can still save a report.',
'Updates use Releases in a public GitHub repository. Startup checks are off by default and optional; manual checks are available. An offline app cannot discover new releases.\nA newer version opens a release-page option, never automatic installation or execution.\nPublishers export publisher.json beside the EXE, then publish a stable tag such as v1.3.0 and the ZIP on GitHub.'],
'es':[
'1. Elija las carpetas de análisis y models de destino; analice todo o solo lo nuevo.\n2. Revise la identificación y los destinos; apruebe, rechace o edite.\n3. Aplique los aprobados. Las carpetas necesarias se crean entonces.\n\nCtrl/Mayús permite selección múltiple. Mantenga el cursor 0,6 segundos para ver la ayuda.',
'Un SHA256 coincidente identifica el mismo archivo, pero no garantiza compatibilidad. Las inferencias y nombres de carpeta se distinguen de resultados verificados.\nCarpetas propias como Img2txtModels necesitan configurar el cargador. Los paquetes de varios archivos se mantienen juntos.\nLa reparación admite determinados cargadores estándar y respalda el JSON original.',
'El modo sin conexión bloquea API, actualizaciones y vistas previas. El análisis local, la caché, la organización y la exportación de registros siguen disponibles.\nLas consultas envían hashes y, en HF, nombres de archivo. No suben pesos ni imágenes.\nLas vistas previas quedan en memoria. Los sitios externos solo se abren cuando usted lo decide.',
'Los registros quedan en el dispositivo; nadie los recibe automáticamente. Se omiten rutas personales, nombres de modelos, credenciales y mensajes de excepción.\nRevise y guarde el informe desde Ayuda y compártalo en el destino de soporte configurado. GitHub Issues es público: revise antes de publicar.\nSin destino configurado, todavía puede guardar el informe.',
'Las actualizaciones usan Releases de un repositorio público de GitHub. La comprobación al iniciar es opcional y está desactivada inicialmente; también puede consultar manualmente. Sin internet no se detectan versiones nuevas.\nSe ofrece abrir la página de la versión, sin instalación ni ejecución automática.\nEl publicador exporta publisher.json junto al EXE y publica una etiqueta estable como v1.3.0 y el ZIP.'],
'zh-CN':[
'1. 选择扫描目录和目标 models 目录，扫描全部或新增项目。\n2. 检查识别结果与目标位置，然后批准、拒绝或编辑。\n3. 执行已批准项目，此时才创建必要的文件夹。\n\n按 Ctrl/Shift 可多选。鼠标停留约 0.6 秒显示提示。',
'SHA256 匹配表示文件相同，不保证运行兼容性。结构推测和现有目录名称与已验证结果分别显示。\nImg2txtModels 等自定义目录还需要配置对应加载节点。多文件模型包不会拆分。\n工作流修复仅支持部分标准加载器，并备份原始 JSON。',
'离线模式阻止 API、更新检查和图片预览请求。本地扫描、缓存信息、整理及日志导出仍可使用。\n在线查询发送哈希，HF 搜索还发送文件名，不上传权重或图片。\n预览只保存在内存中。外部搜索和支持页面仅在您选择时打开。',
'日志保留在设备上，不会自动发送给任何人。不包含个人路径、模型名、凭据或异常详情文本。\n从帮助中检查并保存报告，再由您发送到设置的支持地址。GitHub Issues 是公开内容，发布前请检查。\n未设置发布地址时仍可保存报告。',
'通过公开 GitHub 仓库的 Releases 检查更新。启动时检查默认关闭，可自行启用，也可手动检查。离线时无法发现新版本。\n发现新版后提供版本页面链接，不会自动安装或执行。\n发布者将 publisher.json 导出到 EXE 旁，并在 GitHub 发布如 v1.3.0 的稳定版本标签及 ZIP。'],
'zh-TW':[
'1. 選擇掃描目錄與目標 models 目錄，掃描全部或新增項目。\n2. 檢查辨識結果與目標位置，再核准、拒絕或編輯。\n3. 執行已核准項目，此時才建立必要的資料夾。\n\n按 Ctrl/Shift 可多選。滑鼠停留約 0.6 秒顯示提示。',
'SHA256 符合表示檔案相同，不保證執行相容性。結構推測和現有目錄名稱與已驗證結果分別顯示。\nImg2txtModels 等自訂目錄還需要設定對應載入節點。多檔案模型套件不會拆分。\n工作流程修復僅支援部分標準載入器，並備份原始 JSON。',
'離線模式阻擋 API、更新檢查與圖片預覽請求。本機掃描、快取資訊、整理及記錄匯出仍可使用。\n線上查詢傳送雜湊，HF 搜尋也傳送檔名，不上傳權重或圖片。\n預覽只保存在記憶體中。外部搜尋與支援頁面僅在您選擇時開啟。',
'記錄保留在裝置上，不會自動傳送給任何人。不包含個人路徑、模型名稱、憑證或例外詳細訊息。\n從說明中檢查並儲存報告，再由您傳送到設定的支援位址。GitHub Issues 為公開內容，發布前請檢查。\n未設定發布位址時仍可儲存報告。',
'透過公開 GitHub 儲存庫的 Releases 檢查更新。啟動時檢查預設關閉，可自行啟用，也可手動檢查。離線時無法發現新版本。\n發現新版後提供版本頁面連結，不會自動安裝或執行。\n發布者將 publisher.json 匯出到 EXE 旁，並在 GitHub 發布如 v1.3.0 的穩定版本標籤及 ZIP。'],
 'th':[
'1. เลือกโฟลเดอร์ตรวจสอบและ models ปลายทาง แล้วตรวจทั้งหมดหรือเฉพาะรายการใหม่\n2. ตรวจผลการระบุและปลายทาง แล้วอนุมัติ ปฏิเสธ หรือแก้ไข\n3. ดำเนินการเฉพาะที่อนุมัติ โฟลเดอร์ที่จำเป็นจะถูกสร้างในขั้นตอนนี้\n\nใช้ Ctrl/Shift เพื่อเลือกหลายรายการ วางเมาส์ค้าง 0.6 วินาทีเพื่อดูคำอธิบาย',
'SHA256 ที่ตรงกันยืนยันว่าเป็นไฟล์เดียวกัน แต่ไม่รับประกันความเข้ากันได้ การอนุมานโครงสร้างและชื่อโฟลเดอร์จะแยกจากผลที่ยืนยันแล้ว\nโฟลเดอร์กำหนดเอง เช่น Img2txtModels ต้องตั้งค่าโหนดโหลดให้ตรงกัน แพ็กเกจหลายไฟล์จะไม่ถูกแยก\nการแก้เวิร์กโฟลว์รองรับตัวโหลดมาตรฐานบางตัว และสำรอง JSON เดิม',
'โหมดออฟไลน์ปิดคำขอ API การตรวจอัปเดต และภาพตัวอย่าง ยังตรวจไฟล์ในเครื่อง ใช้แคช จัดระเบียบ และส่งออกบันทึกได้\nการค้นหาออนไลน์ส่งแฮช และส่งชื่อไฟล์เมื่อค้น HF ไม่ส่งน้ำหนักโมเดลหรือภาพ\nภาพตัวอย่างอยู่ในหน่วยความจำ เว็บไซต์ภายนอกเปิดเมื่อคุณเลือกเท่านั้น',
'บันทึกอยู่ในอุปกรณ์ ไม่มีใครได้รับโดยอัตโนมัติ ไม่รวมเส้นทางส่วนตัว ชื่อโมเดล ข้อมูลรับรอง หรือข้อความข้อผิดพลาดแบบละเอียด\nตรวจและบันทึกรายงานจากคู่มือ แล้วส่งให้ช่องทางสนับสนุนที่ตั้งค่าไว้ด้วยตนเอง GitHub Issues เป็นสาธารณะ โปรดตรวจสอบก่อนโพสต์\nหากยังไม่ตั้งค่าผู้เผยแพร่ก็ยังบันทึกรายงานได้',
'ตรวจเวอร์ชันจาก Releases ของที่เก็บสาธารณะบน GitHub การตรวจเมื่อเปิดแอปปิดไว้เป็นค่าเริ่มต้นและเปิดได้ตามต้องการ หรือตรวจเองได้ ออฟไลน์จะไม่ทราบเวอร์ชันใหม่\nเมื่อมีเวอร์ชันใหม่จะแสดงลิงก์หน้าเวอร์ชัน ไม่ติดตั้งหรือเรียกใช้อัตโนมัติ\nผู้เผยแพร่ส่งออก publisher.json ไว้ข้าง EXE แล้วเผยแพร่แท็กเสถียร เช่น v1.3.0 และ ZIP บน GitHub']}
GUIDE['de']=[
'1. Quell- und Zielordner wählen und Modelle prüfen.\n2. Identifikation und Ziele kontrollieren, bestätigen, ablehnen oder ändern.\n3. Nur bestätigte Einträge anwenden. Ordner werden erst dabei erstellt.\nCtrl/Shift ermöglicht Mehrfachauswahl. Hinweise erscheinen beim Überfahren mit der Maus.',
'Ein SHA256-Abgleich bestätigt dieselbe Datei, nicht die Kompatibilität. Unbekannte Modelle und Vermutungen bleiben gesondert gekennzeichnet. Eigene Ordner benötigen passende Loader-Einstellungen. Mehrteilige Modelle bleiben zusammen. Workflow-Reparaturen erstellen Sicherungskopien.',
'Offline werden API-Abfragen, Updates und Vorschaubilder blockiert. Lokale Prüfung und gespeicherte Informationen bleiben verfügbar. Online werden Hashes und bei HF Dateinamen übertragen, keine Gewichte oder eigenen Bilder. Vorschaubilder bleiben nur im Arbeitsspeicher.',
'Protokolle bleiben lokal und werden nicht automatisch gesendet. Der Supportbericht enthält keine Modellnamen, persönlichen Pfade oder Zugangsdaten. Bericht prüfen, speichern und selbst an den Herausgeber senden. GitHub Issues sind öffentlich.',
'Updates werden über GitHub Releases geprüft. Die Startprüfung ist optional und zunächst deaktiviert. Offline können neue Versionen nicht erkannt werden. Keine automatische Installation. Herausgeber konfigurieren publisher.json neben der EXE.']

GUIDE['ja'][0]='【基本の流れ】\n1. 調査するフォルダーと整理先modelsを選び、全件調査を押します。サブフォルダーも調べます。この段階では移動しません。\n2. 一覧は上のフォルダーからの相対パスです。右クリックで完全なパスをコピー／フォルダーを開けます。\n3. 移動を承認＝この移動案を実行対象にする。移動しない＝対象から除外。判断を保留＝未決定に戻す。いずれも即移動・削除しません。\n4. 「承認した項目だけ実行」で初めて移動します。「変更なし」は既にその配置なので承認不要です。\n\nプレビュー：今回の調査結果、または別フォルダーを指定して調査し、一覧のモデルをクリックします。左にモデル一覧と説明、右に公開画像を表示します。画像はメモリー内のみです。配布元URLはクリックで開けます。\n\n左下の動くバーは処理中を示します。残り時間・完了率ではありません。入力欄や説明は右クリックでコピーできます。'
GUIDE['ja'][1]='【どのように探すか】\n1. 対応する重みファイルとモデルパッケージをサブフォルダーから列挙します。\n2. ファイル内容全体のSHA256を計算します。同じ内容なら名前が違っても同じハッシュになります。変更のないファイルはキャッシュを利用します。\n3. オンライン照合をオンにすると、Civitaiの公開APIでハッシュ一致を調べます。Hugging Faceはファイル名で候補を探し、公開SHA256と照合します。名前一致だけでは確認済みにしません。\n4. 配布元情報、保存済み分類ルール、ファイルの内部構造を利用して種類と系統を判定します。特定できないものは未判別として表示します。フォルダー名だけでは識別成功としません。\n5. 保存先を提案します。承認されるまでモデルを移動しません。\n\n【互換性】\nLoRAの配布元の系統と、調査済みチェックポイントを比較します。同じ系統も組み合わせ未検証です。別のSDXL派生系統で読み込める場合でも効果は保証できません。\n\n【ワークフロー参照】\nモデルを移動すると、ComfyUIのJSONが古い相対パスを参照する場合があります。この機能は承認済み／実行済みの移動と対応ローダーを照合し、必要な修正を提案します。選択して実行すると元JSONをバックアップします。全カスタムノードには対応しません。\n\n【TXT】\n配布元TXTを作成＝未作成の説明ファイルを作ります。TXTを読みやすく更新＝選択したモデルのアプリ生成TXTをバックアップして作り直します。モデルの重みを更新する機能ではありません。項目名は常に英語です。元の作者の説明文は自動翻訳しません。'
GUIDE['ja'][2]+='\n\n【公開APIのチェック】\n通常はオンのままで使います。オフにすると新しい配布元照合を止め、端末内の情報・キャッシュだけで調査します。ネット接続がない時、通信を控えたい時に使います。これは完全オフラインとは異なり、画像プレビューや更新確認まで止める設定ではありません。すべて止める場合は完全オフラインを使います。'

GUIDE['ja'][0]='【最初にすること】\n1. 調査元と整理先modelsを選び「全件調査」を押します。サブフォルダーも対象です。調査だけでは移動しません。\n2. 移動やハードリンク追加の案がある場合だけ、確認画面が開きます。理由・現在地・移動先・新しく作るフォルダーを確認してください。\n3. 「はい」は賛成として記録、「いいえ」は今回は除外、「保留」は後で判断します。画面を閉じても移動しません。変更不要なモデルには確認を出しません。\n4. 実行したいときに「移動案を確認して整理」を押し、最後の実行確認で進めます。保留はこのとき再確認できます。拒否した案も一覧で選択すると再確認できます。\n\n【調査後に配布元TXTを作る】\n調査が終わりモデルが一覧に出ると「配布元TXTを作成」が表示されます。必要なモデルを選択して押してください。何も選択していない場合は一覧全体が対象です（エラー・拒否は除外）。新規・変更分の調査では今回一覧に出たモデルが対象です。\nモデルの隣に「モデル名.safetensors.source.txt」を1つ作成します。モデル名、種類、系統、配布元URL、SHA256、トリガーワード、作者の説明、公開情報、照合結果、内部メタデータを記録します。取得できない情報は欠ける場合があります。\nツールの「TXTに含める情報」で任意項目を選べます。初期状態はすべてオンなので、そのままで十分です。項目名は英語、作者の説明は原文です。\n既存TXTは作成ボタンでは上書きしません。「TXTを読みやすく更新」は同じTXTを作り直します。バックアップはアプリのデータフォルダーに保存し、モデルの隣に2枚・3枚と増やしません。\n\n【プレビュー・操作】\nプレビュー一覧のモデルをクリックすると説明と画像が切り替わります。フォルダーを指定して調べることもできます。配布元URLをクリックするとブラウザーで開きます。入力欄や説明欄は右クリックでコピーできます。\n一覧のパスは上の指定フォルダーからの相対表示です。右クリックで完全パスのコピー・フォルダーを開けます。左下のバーは処理中を表し、完了率ではありません。'
GUIDE['ja'][2]+='\n\n【ローカル調査の具体例】\n初めて見るSafetensorsでも、内部の重みの名前や形状、記録されたメタデータからLoRAなどの種類や系統を推定できる場合があります。書かれていない作者・配布ページ・トリガーワードを復元できるわけではありません。\n以前オンライン照合したモデルなら、保存済みハッシュ・配布元情報・分類ルールを使えます。ネット接続がないときや、同じファイルを再整理するときに役立ちます。\nローカルLLMや画像生成AIを実行するモードではありません。重みを読み込んで画像を生成せず、ファイルの構造と情報を調べます。\n通常は「ツール → 公開APIで照合」をオンのまま使ってください。モデル本体・画像はアップロードせず、照合用ハッシュとHF検索時のファイル名を送信します。'

GUIDE['ja'][0]+='\n\n【学習用キャプション】\n画像生成やLoRAの学習そのものではなく、画像から学習用の説明TXTを作る準備機能です。解析はローカルComfyUI＋PixAIで行います。連携ノード設置→ComfyUI再起動→モデル・画像フォルダー指定→接続確認→解析の順です。起動ファイルを設定すると、未起動時に起動を試みます。Desktopのホームだけ開いた場合は、その中でComfyUIを起動してください。\n解析結果はまず変更プレビューに表示されます。「この変更を保存」を押すと、画像と同じフォルダー・同じ名前のTXTを作成します。既存TXTは初期状態でスキップです。再解析する場合、更新前TXTはアプリ用caption-backupsに保存します。\nAPIワークフローの書き出しも可能です。本アプリから実行するときは貼り付け不要です。今回は他の画像解析アプリへのAPI連携や、ComfyUI不要の直接推論には対応していません。'
GUIDE['ja'][1]+='\n\n【互換性候補はどこから来るか】\nこのPCの調査履歴catalogと、今回の調査結果から、現在も存在するモデルを表示しています。全ドライブの自動探索でも、チェックポイントを推論用に読み込んだ結果でもありません。新しいPCでは履歴がなく候補が空です。チェックポイント・LoRAフォルダーを指定し「指定フォルダーを追加調査」を押してください。入力したフォルダー内に候補が限定されます。空欄なら過去の調査全体です。\n\n【テキスト編集】\n画像フォルダーを読み込み、一覧をクリックすると画像と同名のTXTを表示します。画像のないTXTも編集できます。編集後は「編集中のTXTを保存」。保存前に外部アプリが変更したファイルは上書きしません。\n複数選択して、先頭／末尾への追加・削除・置換・< >で囲む操作を選び「変更をプレビュー」。前後を確認して保存します。「タグ完全一致」はカンマ区切りのタグ全体だけが対象。「単語境界」は自然文中の語を対象にします。< >を付けるだけでEmbeddingを学習するわけではなく、OneTrainerのplaceholder設定と一致させる必要があります。\n元TXTはcaption-backupsに退避し、モデルの隣にバックアップを増やしません。復元操作では、編集後にさらに変更されたTXTがあると停止します。UTF-8／BOM付きUTF-8／BOM付きUTF-16を扱い、元のエンコーディングを保持します。'
GUIDE['ja'][2]+='\n学習用キャプションのComfyUI連携は、利用者が明示的に開始する同一PC内のHTTP通信（loopback）です。外部サイトへの通信とは分けており、完全オフラインでもローカルComfyUIは利用できます。ComfyUI自体にインストールされた他の拡張機能の通信は、このアプリから制御しません。'


RESTORE_GUIDE = {
 'ja': '\n\n【実行前の警告と復元】\n実行時に保存場所の変更を説明する警告を表示します。「はい」の後にも件数・移動先の最終確認があります。「再度表示しない」はこの説明だけを省略します。変更前ログと最終確認は省略しません。\n変更前に対象の元パス、移動先、ファイル状態、フォルダーの有無を保存します。モデル本体のコピーではありません。\n右端の「履歴・復元」で日時を選ぶと変更前後のパスを表示します。「選択した履歴を元に戻す」で復元します。複数回変更した場合は新しい履歴から順に戻してください。移動後の編集・削除や元パスの競合があると停止します。今回作成した空フォルダーだけを削除し、既存フォルダーや後から入れたファイルは残します。同じタブで警告の表示を再びオンにできます。',
 'en': '\n\nMOVE WARNING AND RESTORE\nA location-change warning appears before execution, followed by the final count/destination confirmation. Do not show again skips only the warning; the journal and final confirmation remain.\nBefore changes, affected original paths, destinations, file state and existing folders are recorded. This is not a backup of model contents.\nIn the rightmost History / Restore tab, select a date to inspect paths and undo. Undo newest changes first. Edited/deleted files or conflicting original paths stop restoration. Only empty folders created by that run are removed; existing folders and later-added files remain. The warning can be re-enabled in this tab.',
 'es': '\n\nADVERTENCIA Y RESTAURACIÓN\nAntes de ejecutar aparece una advertencia sobre cambios de ubicación, seguida de la confirmación final. No mostrar de nuevo omite solo la advertencia; el registro y la confirmación final permanecen.\nAntes de cambiar nada se registran rutas originales, destinos, estado de archivos y carpetas existentes. No es una copia del contenido del modelo.\nEn Historial / Restaurar, la pestaña del extremo derecho, seleccione una fecha para revisar rutas y deshacer. Deshaga primero los cambios más recientes. Los archivos editados/eliminados o conflictos detienen la restauración. Solo se eliminan carpetas vacías creadas en esa ejecución; se conservan las existentes y archivos añadidos después. Puede reactivar la advertencia en esta pestaña.'
}
for code in GUIDE: GUIDE[code][1] += RESTORE_GUIDE.get(code, RESTORE_GUIDE['en'])

GUIDE['pt-BR'] = [
    '1. Escolha as pastas de verificação e de destino e verifique todos os modelos ou apenas os novos.\n2. Confira a identificação e os destinos. Aprove, rejeite ou altere cada proposta.\n3. Aplique apenas os itens aprovados. As pastas necessárias são criadas nessa etapa.\n\nCtrl/Shift seleciona vários itens. Deixe o cursor sobre um botão por cerca de 0,6 segundo para ver a explicação.',
    'O aplicativo lê a estrutura e os metadados dos arquivos e calcula seu SHA256. Uma correspondência com a origem comprova o mesmo arquivo, mas não garante compatibilidade. Inferências de estrutura e nomes de pastas são diferenciados de resultados confirmados.\nPastas personalizadas, como Img2txtModels, também exigem configuração dos nós de carregamento. Pacotes com vários arquivos são mantidos juntos. Corrigir referências de fluxos cria backup do JSON original.\n\nAntes de mover arquivos, aparece um aviso e depois uma confirmação final. Desativar o aviso não desativa o registro nem a confirmação. Os caminhos e o estado dos arquivos são registrados; isso não copia os pesos do modelo. Em Histórico / Restaurar, desfaça primeiro a operação mais recente. Arquivos alterados ou conflitos interrompem a restauração. Apenas pastas vazias criadas pela operação podem ser removidas.',
    'O modo offline bloqueia consultas de API, atualizações e downloads de prévias. Verificações locais, cache, organização e registros continuam disponíveis.\nConsultas online enviam hashes e, na pesquisa do Hugging Face, nomes de arquivos. Não enviam pesos nem imagens. Prévias ficam somente na memória. Criar modelos de fluxo e editar TXT pode ser feito offline. Os fluxos Image to Text são executados separadamente no ComfyUI.',
    'Os registros ficam neste computador e nunca são enviados automaticamente. Relatórios de diagnóstico omitem caminhos pessoais, nomes de modelos, credenciais e detalhes das exceções. Confira o relatório antes de compartilhar.\nEnvie-o ao suporte configurado por sua própria iniciativa. GitHub Issues é público: não publique segredos ou arquivos privados. Sem endereço de suporte configurado, ainda é possível salvar o relatório.',
    'As atualizações são consultadas em Releases de um repositório público do GitHub. Verificar ao iniciar é opcional e vem desativado. Também é possível verificar manualmente. Offline não detecta novas versões.\nO aplicativo abre a página da versão, sem instalar nem executar atualizações automaticamente. O distribuidor inclui publisher.json ao lado do EXE e publica uma versão estável com o ZIP. Sem uma Release estável publicada, ainda não há atualização disponível para consulta.'
]

GUIDE['ja'][1]+='\n\n全件調査の開始前に、元のファイル・フォルダーの場所をscan-historyのJSONへ記録します。調査では移動しません。整理を実行する直前にhistoryへ変更履歴を保存し、その記録へ関連付けます。「履歴・復元」で記録を選ぶかJSONを開き、変更がある場合に表示される「この配置へ戻す」から戻せます。記録は自動表示されるので更新ボタンは不要です。内容のバックアップではなく、変更・削除や外部操作をすべて戻すものではありません。'
GUIDE['pt-BR'][1]+='\n\nAntes da verificação, os locais originais ficam em um JSON em scan-history. Verificar não move arquivos. Antes de aplicar mudanças, um registro em history é vinculado a esse JSON. Em Histórico / Restaurar, selecione o registro ou abra o JSON; Restaurar estes locais aparece quando há mudanças vinculadas. Não é backup do conteúdo e não desfaz todas as alterações externas.'
for code in GUIDE:
 if code not in ('ja','pt-BR'):GUIDE[code][1]+='\n\nBefore scanning, original file/folder locations are recorded in scan-history JSON. Scanning does not move files. Applied changes write a linked journal in history before moving. Select the inventory or open its JSON in History / Restore; a contextual Restore these locations button appears for linked moves. This is not a content backup or a general undo of external changes.'
