"""Current five-chapter usage guide."""
GUIDE={'ja': ['【基本の流れ】\n'
        '1. 調査元と整理先modelsフォルダーを選び「全件調査」を押します。サブフォルダーも対象です。開始前に元のファイル・フォルダーの場所をscan-historyのJSONへ記録します。調査だけでは移動しません。\n'
        '2. 種類・カテゴリ別、または配布元／作者／種類／系統の整理方法を選び、結果と移動先を確認します。移動・ハードリンク追加の提案には「はい」「いいえ」「保留」で回答します。この時点では変更しません。\n'
        '3. 「移動案を確認して整理」で最終確認後、承認した案だけ実行します。必要なフォルダーは実行時に作ります。既に正しい場所にあるモデルは移動不要です。\n'
        '\n'
        '【操作と表示】\n'
        'Ctrl／Shiftで複数選択できます。ボタンに約0.6秒カーソルを置くと説明を表示します。一覧の場所は指定フォルダーからの相対パスです。右クリックで完全パスをコピー、フォルダーを開けます。プレビューでモデルを選ぶと説明と公開画像を表示します。配布元URLはクリックして開けます。右上の進捗バーは0～100%と状態を表示します。Dark／Classicは右上で選び、次回起動にも保存されます。\n'
        '\n'
        '【配布元TXT】\n'
        '調査後「配布元TXTを作成」でモデルの隣にモデル名.safetensors.source.txtを作ります。選択がなければ一覧全体が対象です（エラー・拒否は除外）。種類、系統、配布元、SHA256、トリガーワード、作者の説明などを記録します。取得できない項目は欠けます。「モデルの配布元TXT」で含める情報を選べます。項目名は常に英語、作者の説明は原文です。作成は既存TXTを上書きしません。「TXTを読みやすく更新」は同じファイルを作り直し、元TXTをアプリのデータフォルダーへバックアップします。モデル本体を更新しません。',
        '【識別と互換性】\n'
        '対応ファイルを列挙し、内容全体のSHA256を計算します。同じ内容は別名でも同じハッシュになります。変更のないファイルにはキャッシュを使います。Civitaiは公開APIのハッシュで照合します。Hugging '
        'Faceはファイル名で候補を検索し公開SHA256を確認します。名前一致だけでは確認済みとしません。配布元、分類ルール、内部の重み名・形状・メタデータから種類と系統を判定します。分からないモデルは未判別として表示します。\n'
        'SeaArt／Tensor.Artには本アプリで検証済みの自動逆ハッシュAPIがないため、自動検索対象ではありません。配布ページを手動で登録してください。Tensor.Artのサイト検索には@sha256とハッシュを利用できます。SHA256一致も実際の動作を保証しません。\n'
        '互換性はLoRAとチェックポイントの配布元系統を比較します。同系統は緑、関連するSDXL派生は黄、不明・異なる系統は灰です。読み込み成功や生成品質の保証ではありません。候補はこのPCの調査履歴と今回の結果です。新しいPCではチェックポイント／LoRAフォルダーを指定して追加調査してください。全ドライブを自動探索しません。\n'
        '\n'
        '【Image to TextとEdit Text】\n'
        '画像フォルダーと解析モデル・閾値を選び、接続確認後に実行します。画像フォルダー内にモデル種類名のフォルダーを作り、元画像のハードリンクと同名TXTを保存します。元画像は移動せず、既存TXTは上書きしません。\n'
        '初回は「カスタムノードを導入・更新」で、使用中のComfyUIのcustom_nodesを自動検出または選択し、配置先を確認して導入します。導入・更新後はComfyUIを再起動して接続確認してください。画像・モデル・閾値を選択して直接実行できます。保存先は画像フォルダー内のモデル種類名フォルダーです。一体型／分解版と対応モデルのノードは共通です。ZIP保存は手動導入・別PC用です。モデル本体とComfyUIの必要ライブラリは別途必要です。テンプレートを保存してComfyUIで開く方法も利用できます。既存TXTは上書きしません。\n'
        '\n'
        '【履歴とワークフロー参照】\n'
        '移動前にhistoryへ変更履歴を保存し、調査前のJSONへ関連付けます。「履歴・復元」で記録を選ぶかJSONを開き、関連する移動を元に戻せます。最新の変更から戻してください。編集・削除・パス競合は復元を止めます。モデル内容のバックアップや外部操作全体の取り消しではありません。不要な空フォルダーだけを削除し、中のファイルは消しません。実行警告を非表示にしても履歴と最終確認は残ります。ワークフロー参照は移動で変わったComfyUIの相対パスを対応する標準ローダーで修正し、元JSONをバックアップします。全カスタムノードには対応しません。',
        '【オフラインとプライバシー】\n'
        '完全オフラインは公開API、更新確認、公開画像の取得など外部通信を止めます。端末内の調査、取得済みキャッシュ、整理、テンプレート作成、TXT編集、ログ保存は使えます。\n'
        '「公開APIで照合」をオフにする設定は新しい配布元検索だけを止めます。プレビューや更新まで止めるには完全オフラインを使ってください。通常は公開APIをオンで使用します。\n'
        'オンライン照合はハッシュとHF検索用ファイル名を送信し、重みや画像をアップロードしません。プレビュー画像はメモリー内で表示し、モデルの隣に保存しません。内部構造から種類や系統を推定できても、記録されていない作者、配布元、トリガーワードは復元できません。以前の調査情報があれば再利用できます。ローカル調査はLLMや画像生成AIを実行する機能ではありません。',
        '【サポートと診断ログ】\n'
        '診断ログは端末内へ保存し、自動送信しません。サポートレポートには個人パス、モデル名、認証情報、例外の詳細文を含めません。About → Support & '
        'Updatesで確認・保存し、必要な場合は自分で問い合わせ先へ渡してください。GitHub '
        'Issuesは公開投稿なので、添付内容を確認してください。公開先が未設定でもログ保存はできます。モデル・画像・私的なファイルを問い合わせに添付する必要はありません。',
        '【更新と公開先】\n'
        'About → Support & UpdatesのGitHub '
        'repositoryからプロジェクトを開けます。更新確認は公開GitHubのReleasesを参照します。起動時確認は初期状態でオフ、手動確認も可能です。オフラインでは新版を検出できません。新版はリリースページを案内し、自動インストール・実行しません。\n'
        '配布者はpublisher.jsonをEXEの隣に同梱し、安定版タグとZIPをGitHub '
        'Releasesに公開します。リポジトリへソースを投稿しただけでは更新通知対象になりません。利用者はZIP全体を展開し、_internalをEXEの隣に保持してください。モデル、個人パス、履歴は配布パッケージに含めません。'],
 'en': ['GETTING STARTED\n'
        '1. Choose the scan folder and destination models folder, then Scan all. Subfolders are included. Before '
        'scanning, original file and folder paths are recorded in scan-history JSON. Scanning does not move files.\n'
        '2. Choose organization by type/category or provider / creator / type / family. Review identification and '
        'destinations. Answer Yes, No or Later for proposed moves and hard links. No changes are applied at this '
        'stage.\n'
        '3. Review and organize proposed moves opens final confirmation. Only approved proposals are applied. Required '
        'folders are created then. Models already at the right destination need no move.\n'
        '\n'
        'CONTROLS AND DISPLAY\n'
        'Use Ctrl/Shift to select multiple items. Hover over a button for about 0.6 seconds for help. Table locations '
        'are relative to the selected folder; right-click to copy the full path or open its folder. Select a model in '
        'Preview to see its description and public images. Click a source URL to open it. The upper-right progress bar '
        'shows 0–100% and status. Dark / Classic are saved for the next launch.\n'
        '\n'
        'MODEL SOURCE TXT\n'
        'After scanning, Create source TXT writes model-name.safetensors.source.txt beside the model. With nothing '
        'selected, the list is used, excluding errors and rejected items. It records type, family, source, SHA256, '
        'trigger words, author description and other available information. Missing information cannot be included. '
        'Choose optional fields in Model source TXT. Field names are always English; author descriptions stay in their '
        'original language. Creation does not overwrite existing TXT. Update readable TXT rebuilds the same file and '
        'backs up the original in application data. Model weights are not updated.',
        'IDENTIFICATION AND COMPATIBILITY\n'
        'Supported files are enumerated and their full SHA256 calculated. Identical contents have the same hash even '
        'with different filenames. Unchanged files use cached results. Civitai is checked through its public hash API. '
        'Hugging Face searches filename candidates and verifies public SHA256; a matching name alone is not '
        'verification. Source metadata, classification rules, tensor names/shapes and embedded metadata help identify '
        'type and family. Unidentified models remain visible for review.\n'
        'SeaArt and Tensor.Art have no automatic reverse-hash API verified for this app and are not queried '
        'automatically. Add the original page manually. Tensor.Art website search accepts @sha256 followed by a hash. '
        'Even a verified hash does not guarantee runtime success.\n'
        'Compatibility compares LoRA and checkpoint source families: green for the same family, yellow for related '
        'SDXL families, gray for unknown or different families. It does not guarantee loading or output quality. '
        "Candidates come from this computer's scan history and current results. On a new PC, select checkpoint/LoRA "
        'folders and scan them. The app does not search every drive.\n'
        '\n'
        'IMAGE TO TEXT AND EDIT TEXT\n'
        'Select the image folder, analysis model and thresholds, check the connection, then run. A folder named after '
        'the model type is created inside the image folder, containing image hardlinks and matching TXT. Original '
        'images stay in place; existing TXT is not overwritten.\n'
        'Install / update custom nodes detects candidates or accepts your actual ComfyUI/custom_nodes folder. Confirm '
        'the target, install and restart ComfyUI, then check connection. Combined, Expanded and supported models share '
        'the same nodes. Model weights and runtime dependencies are separate. ZIP export remains available for manual '
        'setup. Direct execution and exported workflows save under the image folder in the model-type subfolder; '
        'existing TXT is preserved.\n'
        'Edit Text displays and edits training TXT with the same name as an image, and can also edit TXT without an '
        'image. Multiple-selection prepend, append, remove, replace and wrapping in < > are reviewed before saving. '
        'Brackets alone do not train an Embedding; match OneTrainer placeholder settings. External changes stop '
        'overwriting. Supported original encodings are preserved and originals are backed up in caption-backups. '
        'Training TXT and model source TXT serve different purposes.\n'
        '\n'
        'HISTORY AND WORKFLOW REFERENCES\n'
        'Before moving, a history journal is saved and linked to the pre-scan inventory. Select a record or open its '
        'JSON in History / Restore to undo linked moves. Undo newest changes first. Edited/deleted files or path '
        'conflicts stop restoration. This is not a model-content backup or a general undo of external actions. Only '
        'unused empty folders are removed, never their files. Hiding the warning does not skip the journal or final '
        'confirmation. Workflow references repair changed ComfyUI relative paths for supported standard loaders and '
        'back up original JSON; not every custom node is supported.',
        'OFFLINE AND PRIVACY\n'
        'Fully offline mode blocks external requests for public APIs, updates and public preview images. Local scans, '
        'cached information, organization, template export, TXT editing and log saving remain available.\n'
        'Turning off public API lookup stops only new source searches. Use fully offline mode to stop preview and '
        'update requests too. Public API lookup is normally enabled.\n'
        'Online lookup sends hashes and filenames for HF search, not model weights or images. Previews are displayed '
        'in memory and are not saved beside models. Internal structure can suggest type/family but cannot recover '
        'unrecorded authors, source pages or trigger words. Previously collected information can be reused. Local '
        'scanning does not run an LLM or image generation AI.',
        'SUPPORT AND DIAGNOSTICS\n'
        'Diagnostic logs stay on the device and are never sent automatically. Support reports omit personal paths, '
        'model names, credentials and detailed exception messages. Review and save a report in About → Support & '
        'Updates, then share it yourself when needed. GitHub Issues are public; inspect attachments before posting. '
        'Reports can be saved without a configured support destination. You do not need to attach models, images or '
        'private files to a support request.',
        'UPDATES AND PUBLICATION\n'
        'GitHub repository in About → Support & Updates opens the project. Update checks read public GitHub Releases. '
        'Startup checks are off by default; manual checks are available. Offline mode cannot detect new releases. A '
        'newer version offers its release page, never automatic installation or execution.\n'
        'Distributors include publisher.json beside the EXE and publish a stable tag and ZIP in GitHub Releases. '
        'Posting source alone does not produce an update notification. Extract the entire ZIP and keep _internal '
        'beside the EXE. Models, personal paths and histories are excluded from distribution packages.'],
 'zh-CN': ['开始使用\n'
           '1. 选择扫描目录与目标 models 目录，点击扫描全部。包含子目录。扫描前将原始文件和目录路径记录到 scan-history JSON；扫描本身不会移动文件。\n'
           '2. 选择按类型／类别，或平台／作者／类型／系列整理。检查识别结果和目标位置，对移动及硬链接建议选择是、否或稍后。此时不修改文件。\n'
           '3. 点击检查并整理移动建议，最终确认后仅执行已批准建议，并创建必要目录。已在正确位置的模型无需移动。\n'
           '\n'
           '操作与显示\n'
           'Ctrl／Shift 可多选；悬停按钮约 0.6 秒显示说明。路径相对于所选目录显示，右键可复制完整路径或打开目录。预览中选择模型可查看说明及公开图片，点击来源链接可打开页面。右上进度显示 0–100% '
           '和状态。Dark／Classic 与配色会保存到下次启动。\n'
           '\n'
           '模型来源 TXT\n'
           '扫描后创建来源 TXT，会在模型旁生成 '
           'model-name.safetensors.source.txt。未选择时处理整个列表，排除错误和拒绝项。记录类型、系列、来源、SHA256、触发词、作者说明等可获取信息；未知信息无法补齐。在模型来源 TXT '
           '中选择可选字段。字段名始终为英语，作者说明保留原文。创建不覆盖已有 TXT；更新可读 TXT 重建同一文件，并在应用数据中备份原文，不更新模型权重。',
           '识别与兼容性\n'
           '枚举支持的文件并计算完整内容的 SHA256。同内容不同文件名仍有相同哈希；未变文件利用缓存。Civitai 使用公开哈希 API，Hugging Face 按文件名查找候选并核对公开 '
           'SHA256；仅名称一致不算验证。结合来源信息、分类规则、权重名称和形状、内部元数据判断类型及系列。无法识别的模型保留供检查。\n'
           'SeaArt／Tensor.Art 没有本应用验证过的自动逆哈希 API，不会自动查询，请手动添加原始页面。Tensor.Art 网站可使用 @sha256 加哈希搜索。哈希验证也不保证运行成功。\n'
           '兼容性比较 LoRA 与 checkpoint 的来源系列：同系列绿色，相关 SDXL 衍生黄色，未知或不同系列灰色。不保证实际加载或生成质量。候选来自本机扫描历史和本次结果；新电脑需指定 '
           'checkpoint／LoRA 目录追加扫描，不自动搜索所有驱动器。\n'
           '\n'
           '选择图片文件夹、分析模型和阈值，确认连接后运行。程序会在图片文件夹内创建以模型类型命名的文件夹，保存原图的硬链接和同名TXT。原图不会移动，已有TXT不会被覆盖。\n'
           '首次使用时，点击Install / update custom '
           'nodes，自动检测或选择实际使用的ComfyUI的custom_nodes文件夹。确认目标后安装，重启ComfyUI并检查连接。选择图片、模型和阈值即可运行。结果保存在图片文件夹内以模型类型命名的子文件夹中。一体型、分解版和支持的模型共用同一组节点。ZIP用于手动安装或其他电脑。模型本体和ComfyUI运行依赖需另行准备。也可导出模板；已有TXT不会覆盖。\n'
           '\n'
           '历史与工作流引用\n'
           '移动前保存 history 日志并关联扫描前清单。在历史／恢复中选记录或打开 '
           'JSON，撤销关联移动，从最新操作开始。文件被编辑、删除或路径冲突时停止。不是权重内容备份，也不能撤销所有外部操作。仅清理不再需要的空目录，不删除其中的文件。隐藏警告不会跳过日志及最终确认。工作流引用修复受支持标准加载器的 '
           'ComfyUI 相对路径并备份原 JSON，不支持所有自定义节点。',
           '离线与隐私\n'
           '完全离线阻止公开 API、更新、公开预览图片等外部请求。本地扫描、缓存、整理、模板导出、TXT 编辑与日志保存仍可使用。\n'
           '关闭公开 API 核对仅停止新的来源搜索；预览和更新也要停止时使用完全离线。通常保持公开 API 开启。\n'
           '在线核对发送哈希及 HF 搜索用文件名，不上传权重或图片。预览仅在内存显示，不保存在模型旁。内部结构可推测类型及系列，但不能恢复未记录的作者、来源页面、触发词。可复用以前取得的信息。本地扫描不运行 LLM '
           '或图像生成 AI。',
           '支持与诊断\n'
           '诊断日志保存在本机，不自动发送。支持报告不含个人路径、模型名、凭据或异常详细信息。在 About → Support & Updates 检查并保存，必要时自行发送。GitHub Issues '
           '公开，发布前检查附件。没有配置支持地址也能保存日志，无需附加模型、图片或私人文件。',
           '更新与发布\n'
           'About → Support & Updates 的 GitHub repository 打开项目。更新检查读取公开 GitHub '
           'Releases，启动检查默认关闭，也可手动检查。离线无法检测新版。新版提供发布页面，不自动安装或执行。\n'
           '发布者将 publisher.json 放在 EXE 旁，并在 GitHub Releases 发布稳定标签及 ZIP。仅提交源码不会触发更新通知。使用者应完整解压 ZIP，保留 EXE 旁的 '
           '_internal。分发包不含模型、个人路径或历史。\n'
           '\n'
           '选择图片文件夹、分析模型和阈值，确认连接后运行。程序会在图片文件夹内创建以模型类型命名的文件夹，保存原图的硬链接和同名TXT。原图不会移动，已有TXT不会被覆盖。'],
 'zh-TW': ['開始使用\n'
           '1. 選擇掃描資料夾與目標 models 資料夾，按掃描全部。包含子資料夾。掃描前將原始檔案及資料夾路徑記錄至 scan-history JSON；掃描本身不移動檔案。\n'
           '2. 選擇按類型／類別，或平台／作者／類型／系列整理。檢查識別結果和目的地，對移動及硬連結建議選擇是、否或稍後。此時不修改檔案。\n'
           '3. 按檢查並整理移動建議，最終確認後僅執行已核准建議，並建立必要資料夾。已在正確位置的模型不需移動。\n'
           '\n'
           '操作與顯示\n'
           'Ctrl／Shift 可多選；懸停按鈕約 0.6 秒顯示說明。路徑相對於所選資料夾顯示，右鍵可複製完整路徑或開啟資料夾。預覽中選擇模型可查看說明及公開圖片，點擊來源連結可開啟頁面。右上進度顯示 0–100% '
           '與狀態。Dark／Classic 及配色儲存至下次啟動。\n'
           '\n'
           '模型來源 TXT\n'
           '掃描後建立來源 TXT，會在模型旁產生 '
           'model-name.safetensors.source.txt。未選擇時處理整個清單，排除錯誤與拒絕項。記錄類型、系列、來源、SHA256、觸發詞、作者說明等可取得資訊；未知資訊無法補齊。在模型來源 TXT '
           '選擇可選欄位。欄位名始終為英語，作者說明保留原文。建立不覆蓋已有 TXT；更新可讀 TXT 重建同一檔案，並於應用程式資料備份原文，不更新模型權重。',
           '識別與相容性\n'
           '列舉支援的檔案並計算完整內容的 SHA256。同內容不同檔名仍有相同雜湊；未變檔案利用快取。Civitai 使用公開雜湊 API，Hugging Face 按檔名尋找候選並核對公開 '
           'SHA256；僅名稱一致不算驗證。結合來源資訊、分類規則、權重名稱及形狀、內部中繼資料判斷類型與系列。無法識別的模型保留供檢查。\n'
           'SeaArt／Tensor.Art 沒有本應用程式驗證過的自動逆雜湊 API，不自動查詢，請手動加入原始頁面。Tensor.Art 網站可用 @sha256 加雜湊搜尋。雜湊驗證亦不保證執行成功。\n'
           '相容性比較 LoRA 與 checkpoint 的來源系列：同系列綠色，相關 SDXL 衍生黃色，未知或不同系列灰色。不保證實際載入或生成品質。候選來自本機掃描歷史與本次結果；新電腦需指定 '
           'checkpoint／LoRA 資料夾追加掃描，不自動搜尋所有磁碟。\n'
           '\n'
           '選擇圖片資料夾、分析模型和閾值，確認連線後執行。程式會在圖片資料夾內建立以模型類型命名的資料夾，儲存原圖的硬連結和同名TXT。原圖不會移動，既有TXT不會被覆寫。\n'
           '首次使用時，點擊Install / update custom '
           'nodes，自動偵測或選擇實際使用的ComfyUI的custom_nodes資料夾。確認目標後安裝，重新啟動ComfyUI並檢查連線。選擇圖片、模型和閾值即可執行。結果儲存在圖片資料夾內以模型類型命名的子資料夾中。一體型、分解版和支援的模型共用同一組節點。ZIP用於手動安裝或其他電腦。模型本體和ComfyUI執行依賴需另行準備。也可匯出範本；既有TXT不會覆寫。\n'
           '\n'
           '歷史與工作流程參照\n'
           '移動前儲存 history 日誌並關聯掃描前清單。在歷史／還原選記錄或開啟 '
           'JSON，撤銷關聯移動，從最新操作開始。檔案被編輯、刪除或路徑衝突時停止。不是權重內容備份，亦不能撤銷所有外部操作。僅清理不再需要的空資料夾，不刪除其中檔案。隱藏警告不跳過日誌及最終確認。工作流程參照修復受支援標準載入器的 '
           'ComfyUI 相對路徑並備份原 JSON，不支援所有自訂節點。',
           '離線與隱私\n'
           '完全離線阻止公開 API、更新、公開預覽圖片等外部請求。本機掃描、快取、整理、範本匯出、TXT 編輯及日誌儲存仍可用。\n'
           '關閉公開 API 核對僅停止新的來源搜尋；預覽和更新亦要停止時，使用完全離線。通常保持公開 API 開啟。\n'
           '線上核對傳送雜湊及 HF 搜尋用檔名，不上傳權重或圖片。預覽僅於記憶體顯示，不儲存在模型旁。內部結構可推測類型與系列，但不能復原未記錄的作者、來源頁面或觸發詞。可重用以前取得的資訊。本機掃描不執行 LLM '
           '或圖像生成 AI。',
           '支援與診斷\n'
           '診斷日誌保存在本機，不自動傳送。支援報告不含個人路徑、模型名稱、憑證或例外詳細資訊。在 About → Support & Updates 檢查並儲存，必要時自行傳送。GitHub Issues '
           '公開，發文前檢查附件。未設定支援地址仍能儲存日誌，不需附上模型、圖片或私人檔案。',
           '更新與發布\n'
           'About → Support & Updates 的 GitHub repository 開啟專案。更新檢查讀取公開 GitHub '
           'Releases，啟動檢查預設關閉，亦可手動檢查。離線無法偵測新版。新版提供發布頁面，不自動安裝或執行。\n'
           '發布者將 publisher.json 放在 EXE 旁，並於 GitHub Releases 發布穩定標籤及 ZIP。僅提交原始碼不會觸發更新通知。使用者應完整解壓縮 ZIP，保留 EXE 旁的 '
           '_internal。散布套件不含模型、個人路徑或歷史。\n'
           '\n'
           '選擇圖片資料夾、分析模型和閾值，確認連線後執行。程式會在圖片資料夾內建立以模型類型命名的資料夾，儲存原圖的硬連結和同名TXT。原圖不會移動，既有TXT不會被覆寫。'],
 'pt-BR': ['PRIMEIROS PASSOS\n'
           '1. Escolha a pasta de verificação e a pasta models de destino; clique em Verificar tudo. As subpastas são '
           'incluídas. Antes da verificação, os caminhos originais são registrados em JSON em scan-history. Verificar '
           'não move arquivos.\n'
           '2. Escolha organização por tipo/categoria ou plataforma / autor / tipo / família. Confira a identificação '
           'e os destinos. Responda Sim, Não ou Depois às propostas de movimento e links físicos. Nada é alterado '
           'nessa etapa.\n'
           '3. Revise e organize as propostas; após a confirmação final, apenas as aprovadas são aplicadas. As pastas '
           'necessárias são criadas então. Modelos já no destino correto não precisam ser movidos.\n'
           '\n'
           'CONTROLES E EXIBIÇÃO\n'
           'Ctrl/Shift permite selecionar vários itens. Deixe o cursor sobre um botão por cerca de 0,6 segundo para '
           'obter ajuda. Os caminhos são relativos à pasta escolhida; clique com o botão direito para copiar o caminho '
           'completo ou abrir a pasta. Na prévia, selecione um modelo para ver sua descrição e imagens públicas. '
           'Clique no link da origem para abrir a página. A barra superior direita mostra 0–100% e o estado. Dark / '
           'Classic e as cores são salvos para a próxima abertura.\n'
           '\n'
           'TXT DA ORIGEM DO MODELO\n'
           'Após verificar, Criar TXT de origem gera model-name.safetensors.source.txt ao lado do modelo. Sem seleção, '
           'usa a lista, exceto erros e rejeitados. Registra tipo, família, origem, SHA256, palavras de ativação, '
           'descrição do autor e outras informações disponíveis. Informações desconhecidas podem faltar. Escolha os '
           'campos opcionais em TXT de origem do modelo. Os nomes dos campos são sempre em inglês; descrições mantêm o '
           'idioma original. Criar não sobrescreve TXT existente. Atualizar TXT legível recria o mesmo arquivo e salva '
           'o original nos dados do aplicativo. Não atualiza os pesos.',
           'IDENTIFICAÇÃO E COMPATIBILIDADE\n'
           'Os arquivos compatíveis são enumerados e seu SHA256 completo é calculado. Conteúdo idêntico tem o mesmo '
           'hash mesmo com outro nome. Arquivos inalterados usam cache. Civitai é consultado pela API pública de hash. '
           'Hugging Face busca candidatos pelo nome e verifica SHA256 público; o nome sozinho não confirma a '
           'identidade. Origem, regras, nomes/formas dos tensores e metadados ajudam a identificar tipo e família. '
           'Modelos não identificados continuam visíveis para revisão.\n'
           'SeaArt e Tensor.Art não têm uma API automática de busca reversa por hash verificada para este aplicativo e '
           'não são consultados automaticamente. Adicione a página original manualmente. No site Tensor.Art, pesquise '
           '@sha256 seguido do hash. Mesmo um hash confirmado não garante funcionamento.\n'
           'A compatibilidade compara as famílias de origem da LoRA e do checkpoint: verde para a mesma família, '
           'amarelo para famílias SDXL relacionadas e cinza para desconhecidas ou diferentes. Não garante carregamento '
           'nem qualidade. Os candidatos vêm do histórico deste computador e dos resultados atuais. Em outro PC, '
           'selecione pastas de checkpoints/LoRAs e verifique-as. O aplicativo não pesquisa todos os discos.\n'
           '\n'
           'IMAGE TO TEXT E EDIT TEXT\n'
           'Selecione a pasta de imagens, o modelo de análise e os limites; verifique a conexão e execute. Uma pasta '
           'com o nome do tipo de modelo será criada dentro da pasta de imagens, contendo links físicos das imagens e '
           'arquivos TXT com os mesmos nomes. As imagens originais não são movidas e os TXT existentes não são '
           'sobrescritos.\n'
           'Na primeira utilização, use Install / update custom nodes para detectar ou selecionar a pasta custom_nodes '
           'da instalação ComfyUI que você realmente usa. Confira o destino antes de instalar. Reinicie o ComfyUI após '
           'instalar ou atualizar os nós e verifique a conexão. Selecione imagens, modelo e limites para executar. A '
           'saída fica na subpasta do tipo de modelo dentro da pasta de imagens. Os nós são compartilhados pelos modos '
           'Combined e Expanded e pelos modelos compatíveis. O ZIP serve para instalação manual ou outro PC. Modelos e '
           'dependências do ComfyUI são separados. A exportação de templates continua disponível; TXT existentes não '
           'são sobrescritos.\n'
           '\n'
           'HISTÓRICO E REFERÊNCIAS DE FLUXO\n'
           'Antes de mover, salva-se um registro em history ligado ao inventário anterior. Selecione o registro ou '
           'abra seu JSON em Histórico / Restaurar para desfazer movimentos vinculados, do mais recente ao mais '
           'antigo. Arquivos editados/excluídos ou conflitos interrompem a restauração. Não é backup do conteúdo dos '
           'modelos nem desfaz toda ação externa. Apenas pastas vazias desnecessárias são removidas, nunca seus '
           'arquivos. Ocultar o aviso não desativa o registro nem a confirmação final. Referências de fluxo corrigem '
           'caminhos relativos ComfyUI para carregadores padrão compatíveis e fazem backup do JSON original; nem todo '
           'nó personalizado é compatível.',
           'OFFLINE E PRIVACIDADE\n'
           'O modo totalmente offline bloqueia solicitações externas de APIs públicas, atualizações e imagens de '
           'prévia. Verificação local, cache, organização, exportação de fluxos, edição TXT e registros continuam '
           'disponíveis.\n'
           'Desativar a consulta de API pública interrompe apenas novas buscas de origem. Para bloquear também prévias '
           'e atualizações, use o modo totalmente offline. Normalmente mantenha a consulta pública ativada.\n'
           'A consulta online envia hashes e nomes de arquivo para a busca HF, nunca pesos nem imagens. Prévias são '
           'exibidas na memória, sem salvar ao lado dos modelos. A estrutura interna pode sugerir tipo/família, mas '
           'não recupera autores, páginas ou palavras de ativação não registrados. Informações anteriores podem ser '
           'reutilizadas. Verificação local não executa LLM nem IA de geração de imagens.',
           'SUPORTE E DIAGNÓSTICO\n'
           'Os registros de diagnóstico ficam neste dispositivo e nunca são enviados automaticamente. Relatórios de '
           'suporte omitem caminhos pessoais, nomes de modelos, credenciais e mensagens detalhadas de exceção. Confira '
           'e salve em About → Support & Updates e compartilhe por sua iniciativa quando necessário. GitHub Issues é '
           'público: confira anexos antes de publicar. É possível salvar sem um endereço de suporte configurado. Não é '
           'necessário anexar modelos, imagens ou arquivos privados.',
           'ATUALIZAÇÕES E PUBLICAÇÃO\n'
           'GitHub repository em About → Support & Updates abre o projeto. A verificação usa GitHub Releases público. '
           'Verificar ao iniciar vem desativado; também há verificação manual. Offline não detecta versões novas. Uma '
           'versão nova oferece a página de lançamento, sem instalação ou execução automática.\n'
           'O distribuidor inclui publisher.json ao lado do EXE e publica uma tag estável e ZIP no GitHub Releases. '
           'Publicar apenas o código não produz notificação de atualização. Extraia todo o ZIP e mantenha _internal ao '
           'lado do EXE. Modelos, caminhos pessoais e históricos não são distribuídos.\n'
           '\n'
           'Selecione a pasta de imagens, o modelo de análise e os limites; verifique a conexão e execute. Uma pasta '
           'com o nome do tipo de modelo será criada dentro da pasta de imagens, contendo links físicos das imagens e '
           'arquivos TXT com os mesmos nomes. As imagens originais não são movidas e os TXT existentes não são '
           'sobrescritos.'],
 'es': ['Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'GETTING STARTED\n'
        '1. Choose the scan folder and destination models folder, then Scan all. Subfolders are included. Before '
        'scanning, original file and folder paths are recorded in scan-history JSON. Scanning does not move files.\n'
        '2. Choose organization by type/category or provider / creator / type / family. Review identification and '
        'destinations. Answer Yes, No or Later for proposed moves and hard links. No changes are applied at this '
        'stage.\n'
        '3. Review and organize proposed moves opens final confirmation. Only approved proposals are applied. Required '
        'folders are created then. Models already at the right destination need no move.\n'
        '\n'
        'CONTROLS AND DISPLAY\n'
        'Use Ctrl/Shift to select multiple items. Hover over a button for about 0.6 seconds for help. Table locations '
        'are relative to the selected folder; right-click to copy the full path or open its folder. Select a model in '
        'Preview to see its description and public images. Click a source URL to open it. The upper-right progress bar '
        'shows 0–100% and status. Dark / Classic are saved for the next launch.\n'
        '\n'
        'MODEL SOURCE TXT\n'
        'After scanning, Create source TXT writes model-name.safetensors.source.txt beside the model. With nothing '
        'selected, the list is used, excluding errors and rejected items. It records type, family, source, SHA256, '
        'trigger words, author description and other available information. Missing information cannot be included. '
        'Choose optional fields in Model source TXT. Field names are always English; author descriptions stay in their '
        'original language. Creation does not overwrite existing TXT. Update readable TXT rebuilds the same file and '
        'backs up the original in application data. Model weights are not updated.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'IDENTIFICATION AND COMPATIBILITY\n'
        'Supported files are enumerated and their full SHA256 calculated. Identical contents have the same hash even '
        'with different filenames. Unchanged files use cached results. Civitai is checked through its public hash API. '
        'Hugging Face searches filename candidates and verifies public SHA256; a matching name alone is not '
        'verification. Source metadata, classification rules, tensor names/shapes and embedded metadata help identify '
        'type and family. Unidentified models remain visible for review.\n'
        'SeaArt and Tensor.Art have no automatic reverse-hash API verified for this app and are not queried '
        'automatically. Add the original page manually. Tensor.Art website search accepts @sha256 followed by a hash. '
        'Even a verified hash does not guarantee runtime success.\n'
        'Compatibility compares LoRA and checkpoint source families: green for the same family, yellow for related '
        'SDXL families, gray for unknown or different families. It does not guarantee loading or output quality. '
        "Candidates come from this computer's scan history and current results. On a new PC, select checkpoint/LoRA "
        'folders and scan them. The app does not search every drive.\n'
        '\n'
        'IMAGE TO TEXT AND EDIT TEXT\n'
        'Seleccione la carpeta de imágenes, el modelo de análisis y los umbrales; compruebe la conexión y ejecute. '
        'Dentro de la carpeta de imágenes se crea una carpeta con el nombre del tipo de modelo, con enlaces físicos a '
        'las imágenes y archivos TXT del mismo nombre. Las imágenes originales no se mueven y los TXT existentes no se '
        'sobrescriben.\n'
        'Edit Text displays and edits training TXT with the same name as an image, and can also edit TXT without an '
        'image. Multiple-selection prepend, append, remove, replace and wrapping in < > are reviewed before saving. '
        'Brackets alone do not train an Embedding; match OneTrainer placeholder settings. External changes stop '
        'overwriting. Supported original encodings are preserved and originals are backed up in caption-backups. '
        'Training TXT and model source TXT serve different purposes.\n'
        '\n'
        'HISTORY AND WORKFLOW REFERENCES\n'
        'Before moving, a history journal is saved and linked to the pre-scan inventory. Select a record or open its '
        'JSON in History / Restore to undo linked moves. Undo newest changes first. Edited/deleted files or path '
        'conflicts stop restoration. This is not a model-content backup or a general undo of external actions. Only '
        'unused empty folders are removed, never their files. Hiding the warning does not skip the journal or final '
        'confirmation. Workflow references repair changed ComfyUI relative paths for supported standard loaders and '
        'back up original JSON; not every custom node is supported.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'OFFLINE AND PRIVACY\n'
        'Fully offline mode blocks external requests for public APIs, updates and public preview images. Local scans, '
        'cached information, organization, template export, TXT editing and log saving remain available.\n'
        'Turning off public API lookup stops only new source searches. Use fully offline mode to stop preview and '
        'update requests too. Public API lookup is normally enabled.\n'
        'Online lookup sends hashes and filenames for HF search, not model weights or images. Previews are displayed '
        'in memory and are not saved beside models. Internal structure can suggest type/family but cannot recover '
        'unrecorded authors, source pages or trigger words. Previously collected information can be reused. Local '
        'scanning does not run an LLM or image generation AI.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'SUPPORT AND DIAGNOSTICS\n'
        'Diagnostic logs stay on the device and are never sent automatically. Support reports omit personal paths, '
        'model names, credentials and detailed exception messages. Review and save a report in About → Support & '
        'Updates, then share it yourself when needed. GitHub Issues are public; inspect attachments before posting. '
        'Reports can be saved without a configured support destination. You do not need to attach models, images or '
        'private files to a support request.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'UPDATES AND PUBLICATION\n'
        'GitHub repository in About → Support & Updates opens the project. Update checks read public GitHub Releases. '
        'Startup checks are off by default; manual checks are available. Offline mode cannot detect new releases. A '
        'newer version offers its release page, never automatic installation or execution.\n'
        'Distributors include publisher.json beside the EXE and publish a stable tag and ZIP in GitHub Releases. '
        'Posting source alone does not produce an update notification. Extract the entire ZIP and keep _internal '
        'beside the EXE. Models, personal paths and histories are excluded from distribution packages.\n'
        '\n'
        'Seleccione la carpeta de imágenes, el modelo de análisis y los umbrales; compruebe la conexión y ejecute. '
        'Dentro de la carpeta de imágenes se crea una carpeta con el nombre del tipo de modelo, con enlaces físicos a '
        'las imágenes y archivos TXT del mismo nombre. Las imágenes originales no se mueven y los TXT existentes no se '
        'sobrescriben.'],
 'de': ['Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'GETTING STARTED\n'
        '1. Choose the scan folder and destination models folder, then Scan all. Subfolders are included. Before '
        'scanning, original file and folder paths are recorded in scan-history JSON. Scanning does not move files.\n'
        '2. Choose organization by type/category or provider / creator / type / family. Review identification and '
        'destinations. Answer Yes, No or Later for proposed moves and hard links. No changes are applied at this '
        'stage.\n'
        '3. Review and organize proposed moves opens final confirmation. Only approved proposals are applied. Required '
        'folders are created then. Models already at the right destination need no move.\n'
        '\n'
        'CONTROLS AND DISPLAY\n'
        'Use Ctrl/Shift to select multiple items. Hover over a button for about 0.6 seconds for help. Table locations '
        'are relative to the selected folder; right-click to copy the full path or open its folder. Select a model in '
        'Preview to see its description and public images. Click a source URL to open it. The upper-right progress bar '
        'shows 0–100% and status. Dark / Classic are saved for the next launch.\n'
        '\n'
        'MODEL SOURCE TXT\n'
        'After scanning, Create source TXT writes model-name.safetensors.source.txt beside the model. With nothing '
        'selected, the list is used, excluding errors and rejected items. It records type, family, source, SHA256, '
        'trigger words, author description and other available information. Missing information cannot be included. '
        'Choose optional fields in Model source TXT. Field names are always English; author descriptions stay in their '
        'original language. Creation does not overwrite existing TXT. Update readable TXT rebuilds the same file and '
        'backs up the original in application data. Model weights are not updated.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'IDENTIFICATION AND COMPATIBILITY\n'
        'Supported files are enumerated and their full SHA256 calculated. Identical contents have the same hash even '
        'with different filenames. Unchanged files use cached results. Civitai is checked through its public hash API. '
        'Hugging Face searches filename candidates and verifies public SHA256; a matching name alone is not '
        'verification. Source metadata, classification rules, tensor names/shapes and embedded metadata help identify '
        'type and family. Unidentified models remain visible for review.\n'
        'SeaArt and Tensor.Art have no automatic reverse-hash API verified for this app and are not queried '
        'automatically. Add the original page manually. Tensor.Art website search accepts @sha256 followed by a hash. '
        'Even a verified hash does not guarantee runtime success.\n'
        'Compatibility compares LoRA and checkpoint source families: green for the same family, yellow for related '
        'SDXL families, gray for unknown or different families. It does not guarantee loading or output quality. '
        "Candidates come from this computer's scan history and current results. On a new PC, select checkpoint/LoRA "
        'folders and scan them. The app does not search every drive.\n'
        '\n'
        'IMAGE TO TEXT AND EDIT TEXT\n'
        'Wählen Sie den Bildordner, das Analysemodell und die Schwellenwerte, prüfen Sie die Verbindung und starten '
        'Sie. Im Bildordner wird ein nach dem Modelltyp benannter Ordner mit Hardlinks der Bilder und gleichnamigen '
        'TXT-Dateien erstellt. Originalbilder bleiben am ursprünglichen Ort; vorhandene TXT-Dateien werden nicht '
        'überschrieben.\n'
        'Edit Text displays and edits training TXT with the same name as an image, and can also edit TXT without an '
        'image. Multiple-selection prepend, append, remove, replace and wrapping in < > are reviewed before saving. '
        'Brackets alone do not train an Embedding; match OneTrainer placeholder settings. External changes stop '
        'overwriting. Supported original encodings are preserved and originals are backed up in caption-backups. '
        'Training TXT and model source TXT serve different purposes.\n'
        '\n'
        'HISTORY AND WORKFLOW REFERENCES\n'
        'Before moving, a history journal is saved and linked to the pre-scan inventory. Select a record or open its '
        'JSON in History / Restore to undo linked moves. Undo newest changes first. Edited/deleted files or path '
        'conflicts stop restoration. This is not a model-content backup or a general undo of external actions. Only '
        'unused empty folders are removed, never their files. Hiding the warning does not skip the journal or final '
        'confirmation. Workflow references repair changed ComfyUI relative paths for supported standard loaders and '
        'back up original JSON; not every custom node is supported.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'OFFLINE AND PRIVACY\n'
        'Fully offline mode blocks external requests for public APIs, updates and public preview images. Local scans, '
        'cached information, organization, template export, TXT editing and log saving remain available.\n'
        'Turning off public API lookup stops only new source searches. Use fully offline mode to stop preview and '
        'update requests too. Public API lookup is normally enabled.\n'
        'Online lookup sends hashes and filenames for HF search, not model weights or images. Previews are displayed '
        'in memory and are not saved beside models. Internal structure can suggest type/family but cannot recover '
        'unrecorded authors, source pages or trigger words. Previously collected information can be reused. Local '
        'scanning does not run an LLM or image generation AI.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'SUPPORT AND DIAGNOSTICS\n'
        'Diagnostic logs stay on the device and are never sent automatically. Support reports omit personal paths, '
        'model names, credentials and detailed exception messages. Review and save a report in About → Support & '
        'Updates, then share it yourself when needed. GitHub Issues are public; inspect attachments before posting. '
        'Reports can be saved without a configured support destination. You do not need to attach models, images or '
        'private files to a support request.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'UPDATES AND PUBLICATION\n'
        'GitHub repository in About → Support & Updates opens the project. Update checks read public GitHub Releases. '
        'Startup checks are off by default; manual checks are available. Offline mode cannot detect new releases. A '
        'newer version offers its release page, never automatic installation or execution.\n'
        'Distributors include publisher.json beside the EXE and publish a stable tag and ZIP in GitHub Releases. '
        'Posting source alone does not produce an update notification. Extract the entire ZIP and keep _internal '
        'beside the EXE. Models, personal paths and histories are excluded from distribution packages.\n'
        '\n'
        'Wählen Sie den Bildordner, das Analysemodell und die Schwellenwerte, prüfen Sie die Verbindung und starten '
        'Sie. Im Bildordner wird ein nach dem Modelltyp benannter Ordner mit Hardlinks der Bilder und gleichnamigen '
        'TXT-Dateien erstellt. Originalbilder bleiben am ursprünglichen Ort; vorhandene TXT-Dateien werden nicht '
        'überschrieben.'],
 'th': ['Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'GETTING STARTED\n'
        '1. Choose the scan folder and destination models folder, then Scan all. Subfolders are included. Before '
        'scanning, original file and folder paths are recorded in scan-history JSON. Scanning does not move files.\n'
        '2. Choose organization by type/category or provider / creator / type / family. Review identification and '
        'destinations. Answer Yes, No or Later for proposed moves and hard links. No changes are applied at this '
        'stage.\n'
        '3. Review and organize proposed moves opens final confirmation. Only approved proposals are applied. Required '
        'folders are created then. Models already at the right destination need no move.\n'
        '\n'
        'CONTROLS AND DISPLAY\n'
        'Use Ctrl/Shift to select multiple items. Hover over a button for about 0.6 seconds for help. Table locations '
        'are relative to the selected folder; right-click to copy the full path or open its folder. Select a model in '
        'Preview to see its description and public images. Click a source URL to open it. The upper-right progress bar '
        'shows 0–100% and status. Dark / Classic are saved for the next launch.\n'
        '\n'
        'MODEL SOURCE TXT\n'
        'After scanning, Create source TXT writes model-name.safetensors.source.txt beside the model. With nothing '
        'selected, the list is used, excluding errors and rejected items. It records type, family, source, SHA256, '
        'trigger words, author description and other available information. Missing information cannot be included. '
        'Choose optional fields in Model source TXT. Field names are always English; author descriptions stay in their '
        'original language. Creation does not overwrite existing TXT. Update readable TXT rebuilds the same file and '
        'backs up the original in application data. Model weights are not updated.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'IDENTIFICATION AND COMPATIBILITY\n'
        'Supported files are enumerated and their full SHA256 calculated. Identical contents have the same hash even '
        'with different filenames. Unchanged files use cached results. Civitai is checked through its public hash API. '
        'Hugging Face searches filename candidates and verifies public SHA256; a matching name alone is not '
        'verification. Source metadata, classification rules, tensor names/shapes and embedded metadata help identify '
        'type and family. Unidentified models remain visible for review.\n'
        'SeaArt and Tensor.Art have no automatic reverse-hash API verified for this app and are not queried '
        'automatically. Add the original page manually. Tensor.Art website search accepts @sha256 followed by a hash. '
        'Even a verified hash does not guarantee runtime success.\n'
        'Compatibility compares LoRA and checkpoint source families: green for the same family, yellow for related '
        'SDXL families, gray for unknown or different families. It does not guarantee loading or output quality. '
        "Candidates come from this computer's scan history and current results. On a new PC, select checkpoint/LoRA "
        'folders and scan them. The app does not search every drive.\n'
        '\n'
        'IMAGE TO TEXT AND EDIT TEXT\n'
        'เลือกโฟลเดอร์ภาพ โมเดลวิเคราะห์ และค่าเกณฑ์ ตรวจสอบการเชื่อมต่อแล้วเริ่มทำงาน '
        'ระบบจะสร้างโฟลเดอร์ตามชื่อประเภทโมเดลภายในโฟลเดอร์ภาพ เพื่อบันทึกฮาร์ดลิงก์ของภาพต้นฉบับและไฟล์ TXT '
        'ชื่อเดียวกัน ภาพต้นฉบับจะไม่ถูกย้าย และไฟล์ TXT ที่มีอยู่จะไม่ถูกเขียนทับ\n'
        'Edit Text displays and edits training TXT with the same name as an image, and can also edit TXT without an '
        'image. Multiple-selection prepend, append, remove, replace and wrapping in < > are reviewed before saving. '
        'Brackets alone do not train an Embedding; match OneTrainer placeholder settings. External changes stop '
        'overwriting. Supported original encodings are preserved and originals are backed up in caption-backups. '
        'Training TXT and model source TXT serve different purposes.\n'
        '\n'
        'HISTORY AND WORKFLOW REFERENCES\n'
        'Before moving, a history journal is saved and linked to the pre-scan inventory. Select a record or open its '
        'JSON in History / Restore to undo linked moves. Undo newest changes first. Edited/deleted files or path '
        'conflicts stop restoration. This is not a model-content backup or a general undo of external actions. Only '
        'unused empty folders are removed, never their files. Hiding the warning does not skip the journal or final '
        'confirmation. Workflow references repair changed ComfyUI relative paths for supported standard loaders and '
        'back up original JSON; not every custom node is supported.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'OFFLINE AND PRIVACY\n'
        'Fully offline mode blocks external requests for public APIs, updates and public preview images. Local scans, '
        'cached information, organization, template export, TXT editing and log saving remain available.\n'
        'Turning off public API lookup stops only new source searches. Use fully offline mode to stop preview and '
        'update requests too. Public API lookup is normally enabled.\n'
        'Online lookup sends hashes and filenames for HF search, not model weights or images. Previews are displayed '
        'in memory and are not saved beside models. Internal structure can suggest type/family but cannot recover '
        'unrecorded authors, source pages or trigger words. Previously collected information can be reused. Local '
        'scanning does not run an LLM or image generation AI.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'SUPPORT AND DIAGNOSTICS\n'
        'Diagnostic logs stay on the device and are never sent automatically. Support reports omit personal paths, '
        'model names, credentials and detailed exception messages. Review and save a report in About → Support & '
        'Updates, then share it yourself when needed. GitHub Issues are public; inspect attachments before posting. '
        'Reports can be saved without a configured support destination. You do not need to attach models, images or '
        'private files to a support request.',
        'Detailed tool instructions are provided in English below. Select English to view the English guide page.\n'
        '\n'
        'UPDATES AND PUBLICATION\n'
        'GitHub repository in About → Support & Updates opens the project. Update checks read public GitHub Releases. '
        'Startup checks are off by default; manual checks are available. Offline mode cannot detect new releases. A '
        'newer version offers its release page, never automatic installation or execution.\n'
        'Distributors include publisher.json beside the EXE and publish a stable tag and ZIP in GitHub Releases. '
        'Posting source alone does not produce an update notification. Extract the entire ZIP and keep _internal '
        'beside the EXE. Models, personal paths and histories are excluded from distribution packages.\n'
        '\n'
        'เลือกโฟลเดอร์ภาพ โมเดลวิเคราะห์ และค่าเกณฑ์ ตรวจสอบการเชื่อมต่อแล้วเริ่มทำงาน '
        'ระบบจะสร้างโฟลเดอร์ตามชื่อประเภทโมเดลภายในโฟลเดอร์ภาพ เพื่อบันทึกฮาร์ดลิงก์ของภาพต้นฉบับและไฟล์ TXT '
        'ชื่อเดียวกัน ภาพต้นฉบับจะไม่ถูกย้าย และไฟล์ TXT ที่มีอยู่จะไม่ถูกเขียนทับ']}
