"""Localized folder-layout descriptions; paths are examples, not translated."""
from locales import CATALOG
from organization_ui import EXISTING,CREATOR
TEXTS={
'en':('1. Model type → Purpose → Base model family','Choose a type folder such as loras, checkpoints or embeddings. Where source metadata supports it, add a purpose folder (LoRA: Character or Copyright(Style); checkpoints: Anime or Realistic), then a base family such as Illustrious, Anima or Pony. Unknown purpose levels are omitted. Pose is not currently an automatic category. Previously confirmed placements and correctly placed files may be retained.','2. Provider → Creator → Model type → Base model family','Group by source website, creator/account, model type and base family. Unknown creators or types stay in their current location. HF accounts can be organizations. ComfyUI search paths may need adjustment. Only empty former folders are removed; files are not deleted. Source TXT moves with its model.'),
'es':('1. Tipo → Uso → Familia','Primero loras, checkpoints o embeddings. Si los metadatos lo permiten, añade el uso (LoRA: Character o Copyright(Style); checkpoints: Anime o Realistic) y la familia, como Illustrious, Anima o Pony. Se omite el uso desconocido. Pose no es una categoría automática. Las ubicaciones confirmadas o correctas pueden conservarse.','2. Sitio → Autor → Tipo → Familia','Agrupa por sitio, autor/cuenta, tipo y familia. Si el autor o tipo es desconocido, conserva la ubicación. HF puede usar organizaciones. Puede ser necesario ajustar las rutas de ComfyUI. Solo se eliminan carpetas antiguas vacías; no archivos. El TXT de origen se mueve con el modelo.'),
'zh-CN':('1. 类型 → 用途 → 模型家族','先按 loras、checkpoints、embeddings 等类型分类。来源信息支持时，再按用途分类（LoRA：Character 或 Copyright(Style)；检查点：Anime 或 Realistic），最后按 Illustrious、Anima、Pony 等家族分类。未知用途层级省略。目前不自动分类 Pose。已确认或正确的原位置可以保留。','2. 来源平台 → 作者 → 类型 → 家族','按来源网站、作者或账号、类型及家族整理。作者或类型不明时保留原位置。HF 账号也可能是组织。可能需要调整 ComfyUI 搜索路径。只删除旧的空文件夹，不删除文件。来源 TXT 随模型移动。'),
'zh-TW':('1. 類型 → 用途 → 模型家族','先按 loras、checkpoints、embeddings 等類型分類。來源資訊支援時，再按用途分類（LoRA：Character 或 Copyright(Style)；檢查點：Anime 或 Realistic），最後按 Illustrious、Anima、Pony 等家族分類。未知用途層級省略。目前不自動分類 Pose。已確認或正確的原位置可以保留。','2. 來源平台 → 作者 → 類型 → 家族','按來源網站、作者或帳號、類型及家族整理。作者或類型不明時保留原位置。HF 帳號也可能是組織。可能需要調整 ComfyUI 搜尋路徑。只刪除舊的空資料夾，不刪除檔案。來源 TXT 隨模型移動。'),
'pt-BR':('1. Tipo → Finalidade → Família','Primeiro loras, checkpoints ou embeddings. Quando os metadados permitem, acrescenta a finalidade (LoRA: Character ou Copyright(Style); checkpoints: Anime ou Realistic) e a família, como Illustrious, Anima ou Pony. Finalidades desconhecidas são omitidas. Pose não é uma categoria automática. Locais confirmados ou corretos podem ser mantidos.','2. Site → Autor → Tipo → Família','Organiza por site, autor/conta, tipo e família. Autor ou tipo desconhecido mantém o local atual. Contas HF podem ser organizações. Pode ser necessário ajustar os caminhos de busca do ComfyUI. Só pastas antigas vazias são removidas, nunca arquivos. O TXT de origem acompanha o modelo.'),
'de':('1. Typ → Zweck → Modellfamilie','Zuerst loras, checkpoints oder embeddings. Bei passenden Quelldaten folgt der Zweck (LoRA: Character oder Copyright(Style); Checkpoints: Anime oder Realistic), dann die Familie wie Illustrious, Anima oder Pony. Unbekannte Zwecke werden ausgelassen. Pose wird derzeit nicht automatisch klassifiziert. Bestätigte oder korrekte Ablagen können bleiben.','2. Plattform → Urheber → Typ → Familie','Nach Website, Urheber/Konto, Typ und Familie ordnen. Unbekannte Urheber oder Typen bleiben am bisherigen Ort. HF-Konten können Organisationen sein. ComfyUI-Suchpfade müssen eventuell angepasst werden. Nur leere alte Ordner werden entfernt, keine Dateien. Quell-TXT wird mit dem Modell verschoben.'),
'th':('1. ประเภท → การใช้งาน → ตระกูลโมเดล','จัดตาม loras, checkpoints หรือ embeddings ก่อน หากข้อมูลต้นทางรองรับ ให้เพิ่มการใช้งาน (LoRA: Character หรือ Copyright(Style); checkpoints: Anime หรือ Realistic) แล้วตามตระกูล เช่น Illustrious, Anima หรือ Pony หากไม่ทราบการใช้งานจะข้ามระดับนี้ ปัจจุบันไม่จัด Pose อัตโนมัติ ตำแหน่งที่ยืนยันแล้วหรือถูกต้องอาจคงเดิม','2. เว็บไซต์ → ผู้สร้าง → ประเภท → ตระกูล','จัดตามเว็บไซต์ ผู้สร้างหรือบัญชี ประเภท และตระกูล หากไม่ทราบผู้สร้างหรือประเภทจะคงตำแหน่งเดิม บัญชี HF อาจเป็นองค์กร อาจต้องปรับเส้นทางค้นหา ComfyUI ลบเฉพาะโฟลเดอร์เก่าที่ว่าง ไม่ลบไฟล์ TXT ข้อมูลต้นทางย้ายไปพร้อมโมเดล'),
}
for code,(title,description,creator_title,creator_description) in TEXTS.items():
 if code not in CATALOG:continue
 CATALOG[code]['1. 種類・カテゴリー別（既存の方法）']=title
 CATALOG[code]['2. 配布サイト・投稿者別']=creator_title
 CATALOG[code][EXISTING]=title+'\n\n'+description+'\n\nmodels / loras / Character / Illustrious / model.safetensors\nmodels / checkpoints / Anime / Anima / model.safetensors\nmodels / embeddings / model.safetensors'
 CATALOG[code][CREATOR]=creator_title+'\n\n'+creator_description+'\n\nmodels / Civitai / creator_name / loras / Illustrious / model.safetensors\nmodels / Hugging Face / account_or_organization / embeddings / SDXL / model.safetensors'
