from locales import CATALOG,LANGS
ROWS='''全件調査|対応する全モデルを調査します。移動はせず、取得済み情報は再利用します。|Inspect all supported models without moving them. Cached results may be reused.|Analiza todos los modelos compatibles sin moverlos. Puede reutilizar la caché.|检查所有支持的模型但不移动，可复用缓存。|檢查所有支援的模型但不移動，可重用快取。|ตรวจสอบโมเดลที่รองรับทั้งหมดโดยไม่ย้าย อาจใช้ผลแคช
新規・変更分を調査|前回から追加・変更されたモデルだけを調査します。|Inspect only models added or changed since the last scan.|Analiza solo modelos nuevos o modificados desde el último análisis.|仅检查上次扫描后新增或修改的模型。|僅檢查上次掃描後新增或修改的模型。|ตรวจสอบเฉพาะโมเดลที่เพิ่มหรือเปลี่ยนจากครั้งก่อน
調査履歴リセット|調査キャッシュを消して再確認できます。モデルと移動履歴は消しません。|Clear lookup caches to recheck models. Model files and undo history remain.|Borra la caché para verificar de nuevo. Conserva modelos e historial.|清除查询缓存以重新验证，保留模型和移动历史。|清除查詢快取以重新驗證，保留模型與移動歷程。|ล้างแคชเพื่อตรวจใหม่ โดยเก็บโมเดลและประวัติย้อนกลับไว้
調査を停止|現在の調査を中止します。通信中は応答待ちが終わるまで時間がかかります。|Cancel the scan. An active request may finish or time out first.|Cancela el análisis. Una petición activa puede tardar en terminar.|取消扫描，正在进行的请求可能需要完成或超时。|取消掃描，進行中的請求可能需要完成或逾時。|ยกเลิกการตรวจสอบ อาจต้องรอคำขอที่กำลังทำงานสิ้นสุด
互換性の候補|選択LoRAと調査済みチェックポイントの系統を比較します。動作保証ではありません。|Compare the selected LoRA with scanned checkpoint families. This is not a compatibility guarantee.|Compara familias del LoRA y checkpoints analizados. No garantiza compatibilidad.|比较所选 LoRA 与已扫描 Checkpoint 的系列，不保证兼容。|比較所選 LoRA 與已掃描 Checkpoint 的系列，不保證相容。|เปรียบเทียบตระกูล LoRA กับ Checkpoint ที่ตรวจแล้ว ไม่รับประกันความเข้ากันได้
プレビュー|一般向けと表示された公開画像をメモリー内に表示します。通信が必要です。|Fetch a public image marked safe and display it in memory. Internet required.|Muestra en memoria una imagen pública marcada segura. Requiere internet.|联网获取标记为安全的公开图片，仅在内存显示。|連網取得標記為安全的公開圖片，僅在記憶體顯示。|โหลดภาพสาธารณะที่ระบุว่าปลอดภัยและแสดงในหน่วยความจำ ต้องใช้อินเทอร์เน็ต
重複を検出|ファイル全体のSHA256を比較します。ハードリンクを区別し、自動削除しません。|Compare full-file SHA256 hashes, distinguish hardlinks, and never auto-delete.|Compara SHA256 completos, distingue enlaces duros y no elimina automáticamente.|比较完整文件 SHA256，区分硬链接，不自动删除。|比較完整檔案 SHA256，區分硬連結，不自動刪除。|เทียบ SHA256 ทั้งไฟล์ แยกฮาร์ดลิงก์ และไม่ลบอัตโนมัติ
ワークフロー参照を確認|承認した移動に伴う参照変更を確認します。選んだJSONだけバックアップして修正します。|Find loader references affected by approved moves. Repair selected JSON with backups.|Detecta referencias afectadas y repara solo los JSON elegidos con respaldo.|检查批准的移动影响的引用，仅备份并修复所选 JSON。|檢查核准的移動影響的參照，僅備份並修復所選 JSON。|ตรวจการอ้างอิงที่ได้รับผลจากการย้าย สำรองและแก้เฉพาะ JSON ที่เลือก
選択を承認|選択項目を実行対象にします。このボタンだけでは移動しません。|Mark selected items for execution. This button does not move files.|Marca los elementos para ejecutar; este botón no mueve archivos.|将所选项目标记为执行对象，此按钮不移动文件。|將所選項目標記為執行對象，此按鈕不移動檔案。|ทำเครื่องหมายรายการให้ดำเนินการ ปุ่มนี้ยังไม่ย้ายไฟล์
選択を拒否|選択項目を今回の移動対象から除外します。|Exclude selected items from this move operation.|Excluye los elementos de esta operación de movimiento.|从本次移动中排除所选项目。|從本次移動中排除所選項目。|ไม่นำรายการที่เลือกไปย้ายในครั้งนี้
保留に戻す|承認・拒否を取り消し、確認待ちに戻します。|Clear approval or rejection and return items to pending.|Quita la aprobación o rechazo y marca pendiente.|撤销批准或拒绝，恢复待定。|撤銷核准或拒絕，恢復待確認。|ยกเลิกการอนุมัติหรือปฏิเสธแล้วกลับไปรอตรวจสอบ
保存先・リンクを変更…|models内の保存先、追加ハードリンク、配布元URLを設定します。|Choose a destination inside models, optional hardlinks and a source URL.|Elige destino en models, enlaces duros opcionales y URL de origen.|设置 models 内的目标位置、可选硬链接和来源 URL。|設定 models 內的目標位置、選用硬連結與來源 URL。|ตั้งปลายทางภายใน models ฮาร์ดลิงก์เพิ่มเติม และ URL แหล่งที่มา
HF配布元を照合…|指定したHugging FaceリポジトリのmainとSHA256を照合します。|Verify SHA256 against main in a specified Hugging Face repository.|Verifica SHA256 contra main del repositorio Hugging Face indicado.|与指定 Hugging Face 仓库 main 中的 SHA256 比较。|與指定 Hugging Face 儲存庫 main 中的 SHA256 比較。|เทียบ SHA256 กับ main ของที่เก็บ Hugging Face ที่ระบุ
配布元TXTを作成|配布元・トリガーワード・メタデータをモデルの隣に保存します。既存TXTは保護します。|Save source, triggers and metadata beside the model. Existing TXT files are preserved.|Guarda origen, activadores y metadatos junto al modelo. Conserva TXT existentes.|在模型旁保存来源、触发词和元数据，保留现有 TXT。|在模型旁儲存來源、觸發詞與中繼資料，保留現有 TXT。|บันทึกแหล่งที่มา คำกระตุ้น และเมทาดาทาข้างโมเดล เก็บ TXT เดิมไว้
承認した項目だけ実行…|最終確認後にモデルを移動し、必要なフォルダーを作成します。|After confirmation, move approved models and create required folders.|Tras confirmar, mueve modelos aprobados y crea carpetas necesarias.|最终确认后移动已批准模型并创建必要文件夹。|最終確認後移動已核准模型並建立必要資料夾。|หลังยืนยัน จะย้ายโมเดลที่อนุมัติและสร้างโฟลเดอร์ที่จำเป็น
履歴から元に戻す…|移動履歴を使って元の場所へ戻します。変更や競合があれば停止します。|Restore original locations from move history. Stop on modifications or conflicts.|Restaura ubicaciones desde el historial. Se detiene ante cambios o conflictos.|根据历史还原位置，遇到更改或冲突会停止。|依歷程還原位置，遇到變更或衝突會停止。|คืนตำแหน่งเดิมจากประวัติ หยุดหากมีการเปลี่ยนแปลงหรือขัดแย้ง
一覧を保存…|表示対象の調査結果をCSVへ保存します。ローカルパスを含むため共有前に確認してください。|Export scan results to CSV. Review local paths before sharing.|Exporta resultados a CSV. Revise las rutas locales antes de compartir.|导出扫描结果为 CSV，共享前请检查其中的本地路径。|匯出掃描結果為 CSV，分享前請檢查其中的本機路徑。|ส่งออกผลเป็น CSV ตรวจเส้นทางในเครื่องก่อนแชร์
識別結果|未判別・推定・通信失敗・確認済みの件数と根拠を確認します。|Review unidentified, inferred, failed and verified results with evidence.|Revisa resultados desconocidos, inferidos, fallidos y verificados.|查看未知、推测、失败和已验证的结果与依据。|查看未知、推測、失敗及已驗證的結果與依據。|ดูผลที่ไม่ทราบ อนุมาน ล้มเหลว และยืนยันแล้วพร้อมหลักฐาน
通信診断・サポートログ…|個人のパスやモデル名を含まない診断情報を確認・保存します。自動送信しません。|Review and save diagnostics without personal paths or model names. No automatic upload.|Revisa y guarda diagnósticos sin rutas personales ni nombres. Sin envío automático.|查看并保存不含个人路径或模型名的诊断，不自动上传。|查看並儲存不含個人路徑或模型名稱的診斷，不自動上傳。|ดูและบันทึกข้อมูลวินิจฉัยที่ไม่มีเส้นทางส่วนตัวหรือชื่อโมเดล ไม่อัปโหลดอัตโนมัติ
SeaArt・その他の配布元を検索…|ブラウザーで外部サイトを開きます。自動ハッシュ照合とは別です。|Open source websites in your browser, separately from automatic hash verification.|Abre sitios en el navegador; no es verificación automática de hash.|在浏览器打开来源网站，与自动哈希验证不同。|在瀏覽器開啟來源網站，與自動雜湊驗證不同。|เปิดเว็บไซต์แหล่งที่มาในเบราว์เซอร์ แยกจากการตรวจแฮชอัตโนมัติ
__entry|この欄の値を入力・編集できます。フォルダー欄は選択ボタンも使えます。|Enter or edit this value. Folder fields also support Browse.|Introduzca o edite el valor. Para carpetas también puede usar Examinar.|输入或编辑此值，文件夹字段也可使用浏览按钮。|輸入或編輯此值，資料夾欄位也可使用瀏覽按鈕。|กรอกหรือแก้ไขค่า ช่องโฟลเดอร์ใช้ปุ่มเรียกดูได้
__choice|一覧から設定を選びます。選択だけではモデルを移動しません。|Choose an option. Selection alone does not move models.|Elija una opción. Seleccionar no mueve modelos.|从列表选择设置，选择本身不会移动模型。|從清單選擇設定，選擇本身不會移動模型。|เลือกตัวเลือก การเลือกอย่างเดียวไม่ย้ายโมเดล
❔|ガイド、更新、問い合わせ先、プライバシー設定を開きます。|Open the guide, updates, support and privacy settings.|Abre guía, actualizaciones, soporte y privacidad.|打开指南、更新、支持与隐私设置。|開啟指南、更新、支援與隱私設定。|เปิดคู่มือ อัปเดต การสนับสนุน และความเป็นส่วนตัว
'''
TIPS={}
for line in ROWS.splitlines():
 parts=line.split('|')
 if len(parts)!=7:raise ValueError(line)
 key=parts[0];ja=parts[1];TIPS[key]=ja
 for code,text in zip(LANGS,parts[1:]):CATALOG[code][ja]=text
TIPS['__button']='クリックして操作を開始します。移動や修正が必要な操作では確認画面が表示されます。'
for code,text in zip(LANGS,[TIPS['__button'],'Click to begin. Operations that move or modify files show a confirmation.','Pulse para comenzar. Las operaciones que mueven o modifican archivos piden confirmación.','点击开始，移动或修改文件的操作会要求确认。','點選開始，移動或修改檔案的操作會要求確認。','คลิกเพื่อเริ่ม การย้ายหรือแก้ไฟล์จะแสดงการยืนยัน']):CATALOG[code][TIPS['__button']]=text
FIELD_ROWS='''調査するフォルダー|このフォルダーとサブフォルダー内の対応モデルを調べます。|Inspect supported models in this folder and its subfolders.|Analiza modelos compatibles en esta carpeta y sus subcarpetas.|检查此文件夹及子文件夹内支持的模型。|檢查此資料夾及子資料夾內支援的模型。|ตรวจสอบโมเดลที่รองรับในโฟลเดอร์นี้และโฟลเดอร์ย่อย
整理先の models フォルダー|整理先の基点です。提案される保存先はこの中に限定されます。|Destination root. Proposed locations are restricted to this folder.|Carpeta raíz de destino. Las ubicaciones propuestas quedan dentro.|目标根目录，建议位置限制在此目录内。|目標根目錄，建議位置限制在此目錄內。|โฟลเดอร์หลักปลายทาง ตำแหน่งที่เสนออยู่ภายในนี้เท่านั้น
判断|承認・拒否・保留の状態です。承認した項目だけを実行します。|Approval, rejection or pending state. Only approved items are applied.|Estado aprobado, rechazado o pendiente. Solo se aplican aprobados.|批准、拒绝或待定状态，仅执行已批准项目。|核准、拒絕或待確認狀態，僅執行已核准項目。|สถานะอนุมัติ ปฏิเสธ หรือรอ ดำเนินการเฉพาะที่อนุมัติ
モデル／ファイル|モデルファイルの名前です。フォルダーパッケージはまとめて扱います。|Model filename. Folder packages are handled as one unit.|Nombre del archivo. Los paquetes se tratan como una unidad.|模型文件名，文件夹模型包作为整体处理。|模型檔名，資料夾模型套件作為整體處理。|ชื่อไฟล์โมเดล แพ็กเกจโฟลเดอร์จัดการเป็นหน่วยเดียว
種類|LoRA・Embeddingなどの役割です。未判別や構造推定を区別してください。|Role such as LoRA or embedding. Distinguish unknown or inferred types.|Función como LoRA o embedding. Distinga tipos desconocidos o inferidos.|LoRA、Embedding 等作用，请区分未知或推测类型。|LoRA、Embedding 等用途，請區分未知或推測類型。|บทบาทเช่น LoRA หรือ embedding แยกประเภทที่ไม่ทราบหรืออนุมาน
系統|配布元のベースモデル系列です。同じ系列でも互換性は保証されません。|Base model family from the source. Same family does not guarantee compatibility.|Familia del modelo base. No garantiza compatibilidad entre miembros.|来源的基础模型系列，同系列也不保证兼容。|來源的基礎模型系列，同系列也不保證相容。|ตระกูลโมเดลพื้นฐานจากแหล่งที่มา ตระกูลเดียวกันไม่รับประกันความเข้ากันได้
根拠の確かさ|配布元一致・確認済みルール・構造推定・未判別などの判定根拠です。|Source match, reviewed rule, structural inference or unknown evidence.|Coincidencia de origen, regla revisada, inferencia o estado desconocido.|来源匹配、已确认规则、结构推测或未知等依据。|來源符合、已確認規則、結構推測或未知等依據。|หลักฐานการตรงกับแหล่งที่มา กฎที่ตรวจแล้ว การอนุมาน หรือไม่ทราบ
現在の場所|調査時点でのファイルの場所です。|File location when scanned.|Ubicación del archivo al analizarlo.|扫描时的文件位置。|掃描時的檔案位置。|ตำแหน่งไฟล์ขณะตรวจสอบ
移動先|提案する保存先です。実行前に変更できます。|Proposed destination. Editable before applying.|Destino propuesto. Editable antes de aplicar.|建议的目标位置，可在执行前更改。|建議的目標位置，可在執行前變更。|ปลายทางที่เสนอ แก้ไขได้ก่อนดำเนินการ
'''
for line in FIELD_ROWS.splitlines():
 parts=line.split('|');key=parts[0];TIPS[key]=parts[1]
 for code,text in zip(LANGS,parts[1:]):CATALOG[code][parts[1]]=text

from locales_pt_br import register as register_pt_br
register_pt_br(CATALOG, LANGS)
